In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.37935658, 0.08888376, 0.75122216, 0.78215913, 0.15937422])

In [20]:
np.random.rand(5,5)

array([[0.82767861, 0.65362791, 0.80967584, 0.36607272, 0.6643603 ],
       [0.73742086, 0.00648345, 0.52521031, 0.9850299 , 0.50865015],
       [0.60944244, 0.80192089, 0.12887928, 0.4284305 , 0.09704826],
       [0.54915981, 0.55052029, 0.47195916, 0.57240124, 0.70156176],
       [0.84806954, 0.31655874, 0.43205063, 0.65054864, 0.49089587]])

In [23]:
np.random.randn(5)

array([-1.03370801, -0.12310983,  0.3907615 ,  1.61379676,  0.07152505])

In [24]:
np.random.randn(5,5)

array([[-0.58207917,  0.35788628, -1.33184022,  0.63044729, -0.18403944],
       [ 0.13250484, -0.8403222 ,  0.21128286, -0.16549031,  0.44049625],
       [ 0.05151877, -0.09766011, -0.86344881, -0.04314705,  1.27278755],
       [ 0.40036862,  0.20544292, -0.13276805,  0.10643468,  0.20025066],
       [-0.61370926,  0.05167953,  0.7573656 ,  0.02908079,  1.41492171]])

In [26]:
np.random.randint(1,100,10)

array([25, 90, 31, 40, 18, 68, 56, 89, 45,  6])

In [29]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
randr = np.random.randint(0,65,10)
randr

array([11, 22,  0, 53, 20,  0,  0, 20, 34, 31])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
randr.max()

60

In [38]:
randr.argmin()

2

In [42]:
arr.argmax()

24

In [44]:
arr.shape

(25,)

In [45]:
arr.dtype

dtype('int32')